[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.dependencies]
once_cell = "1.21.3"
regex = "1.12.2"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
tempfile = "3"
hex = "0.4"
