[advisories]
db-urls = ["https://advisory.rustsec.org", "https://github.com/RustSec/advisory-db"]
ignore = []

[licenses]
allow = ["MIT", "Apache-2.0", "ISC", "BSD-3-Clause"]
deny = ["GPL-2.0", "GPL-3.0", "LGPL-2.1", "LGPL-3.0"]
exceptions = []

[sources]
allow-git = []
deny-git = []
allow-hosts = ["crates.io", "github.com", "gitlab.com"]
