[package]
name = "pulith"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.54", features = ["derive"] }
clap_complete = "4.5.65"
display_tree = "1.1.2"
once_cell = "1.21.3"
pulith-core = { path = "../pulith-core" }
