[package]
name = "pulith-version"
version = "0.1.0"
edition = "2024"

[dependencies]
semver = { workspace = true }
regex = { workspace = true }
thiserror = { workspace = true }
once_cell = { workspace = true }