[package]
name = "pulith-version"
version = "0.1.0"
edition = "2024"

[dependencies]
semver = { version = "1.0.27", features = ["serde"] }
regex = { workspace = true }
thiserror = { workspace = true }
once_cell = { workspace = true }