[package]
name = "pulith-fetch"
version = "0.2.0"
edition = "2024"
description = "HTTP downloading with streaming verification and atomic placement"

[features]
default = ["reqwest"]
reqwest = ["dep:reqwest"]

[dependencies]
pulith-fs = { path = "../pulith-fs" }
pulith-verify = { path = "../pulith-verify" }

thiserror.workspace = true
hex.workspace = true
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
bytes = "1"

reqwest = { version = "0.13.2", features = [
	"stream",
	"default-tls",
], optional = true }

[dev-dependencies]
tempfile.workspace = true
